# JWT SECRET
token:
  secret: ${JWT_SECRET}
# DB CONFIG
spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    initialization-mode: always
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
    show-sql: true
