# JWT SECRET
token:
  secret: ${JWT_SECRET}
# DB CONFIG
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    initialization-mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
